### ISSUE TITLE
你好,请问一下401错误该怎么解决？

### ISSUE THREAD

**Issue by LuckyMango** [kaimz/blog-source#2]
我在执行部署 命令的时候hexo deploy，就会显示该错误

http://xxxx.cn/test.html
{"error":401,"message":"token is not valid"}
INFO  Deploy done: baidu_url_submitter

**Comment by kaimz** [comment]
在百度站长要注册站长，在自己的网站管理的 站点属性，链接提交，主动提交可以找到 token，
在 根目录 `_config.yml` 文件中配置自己的域名和 token：
![image](https://user-images.githubusercontent.com/25757587/63418224-503d0d80-c435-11e9-88cc-bee3582a2775.png)

如果不需要这个功能可以在  根目录 `_config.yml` 文件中 ：
```yaml
deploy:
- type: git
  repo:
   # github: git@github.com:kaimz/kaimz.github.io.git,master
- type: baidu_url_submitter  # 可以把这一行删掉或者注释掉，就不会主动推动链接到百度站长
```
